USE [fullstackDotNetAngularJS]

CREATE TABLE TB_DADOS_PESSOAIS (
    ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOME_COMPLETO VARCHAR(255) NOT NULL,
	NOME_SOCIAL VARCHAR(255),
	RG VARCHAR(9) NOT NULL, 
	CPF VARCHAR(11) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	ATIVO BIT NOT NULL
);

CREATE TABLE TB_ENDERECO (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,	
	LOGRADOURO VARCHAR(255) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	CIDADE VARCHAR(255) NOT NULL,
	CEP VARCHAR(8) NOT NULL,
	COMPLEMENTO VARCHAR(255),
	ESTADO VARCHAR(2) NOT NULL,
	ID_TB_DADOS_PESSOAIS BIGINT FOREIGN KEY REFERENCES TB_DADOS_PESSOAIS(ID)
);

CREATE TABLE TB_TELEFONES (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,	
	DDD VARCHAR(2) NOT NULL,
	CELULAR VARCHAR(9) NOT NULL,
	RESIDENCIAL VARCHAR(8),
	ID_TB_DADOS_PESSOAIS BIGINT FOREIGN KEY REFERENCES TB_DADOS_PESSOAIS(ID)
);

CREATE TABLE TB_SETOR_REF (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,	
	DESCRICAO VARCHAR(255) NOT NULL	
);

CREATE TABLE TB_CARGO (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,	
	DESCRICAO VARCHAR(255) NOT NULL,
	SALARIO DECIMAL(10,2) NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_ENCERRAMENTO DATE,
	SETOR INT  NOT NULL,
	ID_TB_DADOS_PESSOAIS BIGINT FOREIGN KEY REFERENCES TB_DADOS_PESSOAIS(ID),
	ID_TB_SETOR_REF INT FOREIGN KEY REFERENCES TB_SETOR_REF(ID)
);